### ISSUE TITLE
JOSS Review "Example usage" [Major]

### ISSUE THREAD

**Issue by DannyArends** [scikit-learn-contrib/forest-confidence-interval#31]
1) The examples use two standard datasets from another package, however it is not explained in which 
format the users own data needs to be presented before it can be used. 
Please provide links to the relevant documentations.

2) The two examples do not show before and after plots of the dataset, as 
such it is not clear why the user should use this routine.

3) There is no description of what settings can be used in the calculation of inbag and unbiased variance and how these influence the results

**Comment by kpolimis** [comment]
1. Added: "The example data was imported as a matrix and converted to a data frame and separated into X (predictors) and y matrices (predictions). This module will work for matrices or `pandas` data frames.

2. Added before and after plots

3. Added: "The inbag matrix that fit the data is set to `None` by default, and the inbag will be inferred from the forest. However, this only works for trees for which bootstrapping was set to `True`. That is, if sampling was done with replacement. Otherwise, users need to provide their own inbag matrix."

**Comment by arokem** [comment]
@kpolimis : where are the commits that implement these changes? Please point to a Github link with these changes, so that I can merge them into master.
