### ISSUE TITLE
Receiving strange TypeError

### ISSUE THREAD

**Issue by finbarrtimbers** [scikit-learn-contrib/forest-confidence-interval#40]
I have the following code: 

```
df = pd.read_csv('data.csv', header=0, engine='c')
mat = df.as_matrix()
X = mat[:, 1:]
X_train, X_test = train_test_split(X, test_size = 0.2)
variance = forestci.random_forest_error(model, X_train, X_test)
```

When I run it, it throws the error `TypeError: random_forest_error() takes exactly 4 arguments (3 given)`.

However, there are only three non-optional arguments listed in the [documentation](http://contrib.scikit-learn.org/forest-confidence-interval/reference/forestci.html#wager2014). 
If I add a fourth argument for `inbag`, I then get an error saying that `inbag` is defined twice. Any ideas of what's causing this? I'm happy to write a PR if you point me towards the cause.

**Comment by arokem** [comment]
Thanks for reporting!

How did you install forestci? We did change the API in https://github.com/scikit-learn-contrib/forest-confidence-interval/pull/37, so if you installed from pip, you might want to use the examples as they were before that change (e.g., here: https://github.com/scikit-learn-contrib/forest-confidence-interval/tree/03e9c146eeb7a857764a070ac9ca21f93a137a7e/examples). 

We will also make a new release soon, so that pip installations match the documentation, but we're still also working through some other issues, so it might take us a little bit longer.

**Comment by finbarrtimbers** [comment]
Thanks, that was it. It seems to work now (my machine is killing the process because it takes too much memory, but that's my problem).

**Comment by arokem** [comment]
Might also be related to this PR #39

**Comment by finbarrtimbers** [comment]
Thanks, I'll check that out.
