### ISSUE TITLE
Not compatible with SKLearn version 0.22.1

### ISSUE THREAD

**Issue by csanadpoda** [scikit-learn-contrib/forest-confidence-interval#89]
A newer version of SciKit Learn modified `_generate_sample_indices()` to require an additional `n_samples_bootstrap` argument, thus the current version of the code will raise a `TypeError: _generate_sample_indices() missing 1 required positional argument: 'n_samples_bootstrap'` when running  `fci.random_forest_error(mpg_forest, mpg_X_train, mpg_X_test)`.

**Comment by cewaphi** [comment]
This is due to a change in the function _generate_sample_indices of the scikit-learn package (occured on the change from version 0.21 to 0.22).
The issue has already been solved by a recent commit in the master branch.

Did you install the package with pypi or manually?
I would suggest that you either install the forest-confidence-interval package directly from the master branch or downgrade your scikit-learn version to <0.22

**Comment by csanadpoda** [comment]
I downloaded it via pip, so it seems like pip doesn't have the latest version of this. Since I saw a closed issue related to this, I even tried a pip update, but it said I'm up to date. Are you sure the newest version is available via pip?

**Comment by arokem** [comment]
No. We need to cut a new release. Sorry about that.

For the time being, I believe that a:

    pip install -U git+
https://github.com/scikit-learn-contrib/forest-confidence-interval.git

should set you straight.

**Comment by arokem** [comment]
OK. Just cut a new release. This should be resolved, but let us know if not.
