### ISSUE TITLE
All 0's in `g_eta_raw`.

### ISSUE THREAD

**Issue by m0wer** [scikit-learn-contrib/forest-confidence-interval#93]
Trying to debug the problem of getting all `NaN`'s from `random_forest_error` I found that the `g_eta_raw` array  from https://github.com/scikit-learn-contrib/forest-confidence-interval/blob/bfb97c096287e74728132b8c7923590c2ad518e8/forestci/calibration.py#L101 contains all 0's and then the `g_eta_main` division throws the warning `RuntimeWarning: invalid value encountered in true_divide`.

This is probably related to #72, #78, #83, #88 and #92.

¿Any idea on why, despite `np.exp(np.dot(XX, eta_hat))` and `mask` having some values different from 0, their product is a null matrix (all values are 0)? Of course it's because one of them is 0 in every pair of components (e.g. `np.exp(np.dot(XX, eta_hat)[i]` or `mask[i]` are 0 for every `i` in `range(len(mask))`). But why does this situation occur?

**Comment by el-hult** [comment]
I have spent all morning working on this, and came up with a pull request to hopefully improve the code.

However, I don't know if it really helps. The underlying problem is that the noise characteristics of some ensambles on some datasets are not compatible with the parametric model in the calibration routine. In such cases, the calibration routine should not be used. 

If you get negative variance estimates and the calibration routine fails, you should increase the number of trees in the ensamble until you get something reasonable

**Comment by danieleongari** [comment]
@el-hult I underatand your frustration, the calibration method is fragile and unpredictable due to the sampling procedure, which would require some deterministic and pragmatic choice to be taken (but also would require some testing) when such numerical errors incurr. What I do is to use many trees (10x the number of samples) and skip calibration.

**Comment by el-hult** [comment]
Sorry if the tone came though as frustrated. It was actually quite fun to learn the details, even if took much more time than I hoped. Thanks for the reply anyways. :)

**Comment by danieleongari** [comment]
Improved in v0.7
